export const GET_POKEMON_DETAILS_REQUEST = "GET_POKEMON_DETAILS_REQUEST";
export const GET_POKEMON_DETAILS_SUCCESS = "GET_POKEMON_DETAILS_SUCCESS";
export const GET_POKEMON_DETAILS_FAILURE = "GET_POKEMON_DETAILS_FAILURE";
